### ISSUE TITLE
Installing pash-cmd fails.

### ISSUE THREAD

**Issue by LukasDoesDev** [MattMoony/pash#1]
I got an error while installing `pash-cmd`:
```
ERROR: Could not find a version that satisfies the requirement pash-cmd==0.0.4 (from -r .\requirements.txt (line 7)) (from versions: none)
ERROR: No matching distribution found for pash-cmd==0.0.4 (from -r .\requirements.txt (line 7))
```
I expected it to install properly with no errors.

**Comment by MattMoony** [comment]
Hi,

sorry that you're experiencing such a problem - however, have you made sure that you're using the latest version of pip (as [this](https://stackoverflow.com/questions/49748063/pip-install-fails-for-every-package-could-not-find-a-version-that-satisfies) stackoverflow post suggests) and are you using a Python version >= 3.7 (as this is a requirement of `pash-cmd` 😬)?

In case the problem still persists, please reply! 🙃

**Comment by LukasDoesDev** [comment]
The latest python version i have is 3.6. Didn't know that such new versions exist.

**Comment by MattMoony** [comment]
Okay... if you're willing to update your Python version, please try again and tell me whether or not everything works 👍

**Comment by LukasDoesDev** [comment]
I downloaded Python 3.9 and added to the path. Looking forward to seeing it work. Don't know why i get "Access Denied" errors when i use "python.exe" but "python3.9.exe" works (both files in same folder, double-clicked them too).

**Comment by LukasDoesDev** [comment]
pash-cmd installed successfully!

**Comment by MattMoony** [comment]
Great to hear! 👍 😄

**Comment by LukasDoesDev** [comment]
> are you using a Python version >= 3.7

Did you mean:

```
are you using a Python version <= 3.7
```

**Comment by MattMoony** [comment]
Not quite. In this context I was naming a couple of conditions that have to be true if you want to use `pash` - one of them being that you use a Python version `>=` 3.7. Sorry, if I failed to articulate myself properly :grimacing:

**Comment by LukasDoesDev** [comment]
oops; can't read
